"functions":
- "name": "cgi_handle_request"
  "file": "./cgi.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "url"
    "type": "char*"
  - "name": "pi"
    "type": "struct path_info*"
  "return_type": "static void"
  "signature": "static void cgi_handle_request(struct client *cl, char *url, struct path_info *pi)"
- "name": "__printf"
  "file": "./client.c"
  "params":
  - "name": "param0"
    "type": "4"
  - "name": "param1"
    "type": "5"
  "return_type": "void"
  "signature": "void __printf(4, 5) uh_client_error(struct client *cl, int code, const char *summary, const char *fmt, ...)"
- "name": "client_parse_header"
  "file": "./client.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "data"
    "type": "char*"
  "return_type": "static void"
  "signature": "static void client_parse_header(struct client *cl, char *data)"
- "name": "file_write_cb"
  "file": "./file.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  "return_type": "static void"
  "signature": "static void file_write_cb(struct client *cl)"
- "name": "__handle_file_request"
  "file": "./file.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "url"
    "type": "char*"
  - "name": "is_error_handler"
    "type": "bool"
  "return_type": "static bool"
  "signature": "static bool __handle_file_request(struct client *cl, char *url, bool is_error_handler);  static void uh_file_request(struct client *cl, const char *url, struct path_info *pi, struct blob_attr **tb)"
- "name": "__handle_file_request"
  "file": "./file.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "url"
    "type": "char*"
  - "name": "is_error_handler"
    "type": "bool"
  "return_type": "static bool"
  "signature": "static bool __handle_file_request(struct client *cl, char *url, bool is_error_handler)"
- "name": "uh_handle_request"
  "file": "./file.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  "return_type": "void"
  "signature": "void uh_handle_request(struct client *cl)"
- "name": "handle_redirect"
  "file": "./handler.c"
  "params":
  - "name": "ctx"
    "type": "struct json_script_ctx*"
  - "name": "data"
    "type": "struct blob_attr*"
  "return_type": "static char **cur_url;  static void"
  "signature": "static char **cur_url;  static void handle_redirect(struct json_script_ctx *ctx, struct blob_attr *data)"
- "name": "handle_var"
  "file": "./handler.c"
  "params":
  - "name": "ctx"
    "type": "struct json_script_ctx*"
  - "name": "name"
    "type": "const char*"
  - "name": "vars"
    "type": "struct blob_attr*"
  "return_type": "static const char *"
  "signature": "static const char * handle_var(struct json_script_ctx *ctx, const char *name, struct blob_attr *vars)"
- "name": "proc_handle_close"
  "file": "./proc.c"
  "params":
  - "name": "r"
    "type": "struct relay*"
  - "name": "ret"
    "type": "int"
  "return_type": "static void"
  "signature": "static void proc_handle_close(struct relay *r, int ret)"
- "name": "relay_read_cb"
  "file": "./relay.c"
  "params":
  - "name": "s"
    "type": "struct ustream*"
  - "name": "bytes"
    "type": "int"
  "return_type": "static void"
  "signature": "static void relay_read_cb(struct ustream *s, int bytes)"
- "name": "uh_ubus_handle_get_subscribe"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "path"
    "type": "const char*"
  "return_type": "static void"
  "signature": "static void uh_ubus_handle_get_subscribe(struct client *cl, const char *path)"
- "name": "uh_ubus_handle_get"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  "return_type": "static void"
  "signature": "static void uh_ubus_handle_get(struct client *cl)"
- "name": "uh_ubus_handle_request_object"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "obj"
    "type": "struct json_object*"
  "return_type": "static void"
  "signature": "static void uh_ubus_handle_request_object(struct client *cl, struct json_object *obj)"
- "name": "uh_ubus_handle_post"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  "return_type": "static void"
  "signature": "static void uh_ubus_handle_post(struct client *cl)"
- "name": "uh_ubus_data_send"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "data"
    "type": "const char*"
  - "name": "len"
    "type": "int"
  "return_type": "static int"
  "signature": "static int uh_ubus_data_send(struct client *cl, const char *data, int len)"
- "name": "uh_ubus_handle_request"
  "file": "./ubus.c"
  "params":
  - "name": "cl"
    "type": "struct client*"
  - "name": "url"
    "type": "char*"
  - "name": "pi"
    "type": "struct path_info*"
  "return_type": "static void"
  "signature": "static void uh_ubus_handle_request(struct client *cl, char *url, struct path_info *pi)"